reload_data = true;
if reload_data
    %% Import data from text file
    % Script for importing data from the following text file:
    %
    %    filename: C:\Users\Josh\Documents\Classes\Flight Sim\Excercise_4\Sphere_simulator\Sphere_out.txt
    %
    % Auto-generated by MATLAB on 27-Sep-2023 21:26:52
    
    %% Set up the Import Options and import the data
    opts = delimitedTextImportOptions("NumVariables", 14);
    
    % Specify range and delimiter
    opts.DataLines = [2, Inf];
    opts.Delimiter = ",";
    
    % Specify column names and types
    opts.VariableNames = ["Times", "ufts", "vfts", "wfts", "prads", "qrads", "rrads", "xft", "yft", "zft", "e0rad", "exrad", "eyrad", "ezrad"];
    opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
    
    % Specify file level properties
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";
    
    % Import the data
    Sphereout = readtable("C:\Users\Josh\Documents\Classes\Flight Sim\Excercise_4\Sphere_simulator\Sphere_out.txt", opts);
    
    
    %% Clear temporary variables
    clear opts
end 

%% trajectory plot
x = table2array(Sphereout(:,"xft"));
y = table2array(Sphereout(:,"yft"));
z = -table2array(Sphereout(:,"zft"));
figure
plot3(x,y,z)

grid on;
xlabel("x(ft)");
ylabel("y(ft)")
zlabel("z(ft)")
title("Trajectory")


%% plot velocity
u = table2array(Sphereout(:,"ufts"));
v = table2array(Sphereout(:,"vfts"));
w = table2array(Sphereout(:,"wfts"));
t = table2array(Sphereout(:,"Times"));
figure, plot(t,u,DisplayName="u"); hold on
plot(t,v,DisplayName="v")
plot(t,w,DisplayName="w")
legend
